See live-initrd log

diff --git a/bin/set-console-width b/bin/set-console-width
--- a/bin/set-console-width
+++ b/bin/set-console-width
@@ -72,6 +72,26 @@ set_console_font() {
     local width=${cmd_width##*,}
     : ${width:=$DEF_SCREEN_WIDTH}
 
+    local dir fdir
+    for dir in $FONT_DIRS; do
+        test -d $dir || continue
+        fdir=$dir
+        break
+    done
+    [ -n "$fdir" ] || error "could not find a font directory"
+
+    # The two font dirs and the extension stuff below allows the same code
+    # to work early in the initrd and late while the real system is booting.
+    # The busybox "setfont" doesn't like gzipped fonts so they are not
+    # gzipped in the initrd.  This actually makes the initrd.gz *smaller*.
+    local ext=.psf.gz
+    case $fdir in
+        /live/*) ext=.psf ;;
+    esac
+
+
+
+    local file font face size
     while true; do
         # Silently give up on bad input
         case $width in
@@ -84,23 +104,6 @@ set_console_font() {
         test -e /dev/fb0 || break
 
         local name=Terminus
-
-        # The two font dirs and the extension stuff below allows the same code
-        # to work early in the initrd and late while the real system is booting.
-        # The busybox "setfont" doesn't like gzipped fonts so they are not
-        # gzipped in the initrd.  This actually makes the initrd.gz *smaller*.
-        local dir fdir
-        for dir in $FONT_DIRS; do
-            test -d $dir || continue
-            fdir=$dir
-            break
-        done
-        [ -n "$fdir" ] || error "could not find a font directory"
-
-        local ext=.psf.gz
-        case $fdir in
-            /live/*) ext=.psf ;;
-        esac
 
         local pixel_width=$(get_fbcondecor_width --tty=1)
 
@@ -118,7 +121,6 @@ set_console_font() {
 
         # Convert font parameters to parts of the font name
 
-        local size
         case $cmd_size in
                             [1-7]) size=12x6       ;;
                              [89]) size=16         ;;
@@ -132,7 +134,7 @@ set_console_font() {
 
         # Now try to find an existing font file that matches what we want
 
-        local try font face font_file
+        local try font_file
         for face in ${name}Bold VGA $name; do
             #say $face$size
             try=$code-$face$size
@@ -151,6 +153,8 @@ set_console_font() {
     if [ -z "$font" ]; then
         font=$code-VGA16
         file=$fdir/$font$ext
+        face="VGA"
+        size="8x16"
         test -e $file || return 2
     fi
 
