See live-initrd log

diff --git a/init b/init
--- a/init
+++ b/init
@@ -25,8 +25,8 @@
 # that you don't want users to be able to adjust.
 
                      ME="initrd init"
-                VERSION="8.11.04"
-           VERSION_DATE="Wed Nov  1 11:37:35 MDT 2017"
+                VERSION="8.12.01"
+           VERSION_DATE="Fri Nov  3 20:41:00 MDT 2017"
               DEVELOPER="BitJam"
          BUG_REPORT_URL="liveboot@antixlinux.org"
 
@@ -110,10 +110,10 @@
   LIVE_386_LD_PATH="/lib:/lib/i386-linux-gnu:/usr/lib"
 
 MKFS_FREE_MARGIN=10
-  rootfs_SIZE_PARAM="min_size=250 mid_size=100 max_size=2000 factor=50"
-  homefs_SIZE_PARAM="min_size=10 mid_size=100 max_size=4000 factor=25"
-         MKFS_SIZES="250 375 500 750 1000 1500 2000 2500 3000 4000"
-       BIGGER_SIZES="5000 6000"
+  rootfs_SIZE_PARAM="min_size=250 mid_size=100 max_size=4096 factor=50"
+  homefs_SIZE_PARAM="min_size=10 mid_size=100 max_size=8192 factor=25"
+         MKFS_SIZES="250 375 500 750 1024 1500 2048 2500 3072 4096"
+       BIGGER_SIZES="5120 6144 8192 10240 12288 15360 20480"
       SMALLER_SIZES="10 100 175"
 
       LIVE_SCRIPTS="live-L10n live-init"
@@ -255,6 +255,8 @@ main_wrapper() {
     run_init_scripts $NEW_ROOT $LIVE_SCRIPTS
     PATH=$LIVE_BIN
 
+    decolor_file $NEW_ROOT/var/log/live/live-init.log.color
+
     test -r /late-umount.sh && . /late-umount.sh
     sync
     prep_seed_dev_random "$SEED_FILE"
@@ -277,7 +279,11 @@ main_wrapper() {
                 mount --bind /live/aufs/live/$dir $new_dir
             done
 
-            chmod 700 $NEW_ROOT/live
+            # Leave ext2/3/4 as read-write
+            case $(mntpnt_fstype $NEW_ROOT$BOOT_MP) in
+                ext[234]|iso9660) ;;
+                               *) chmod 700 $NEW_ROOT/live ;;
+            esac
         fi
     fi
 
@@ -453,9 +459,6 @@ main_core() {
         debug_cmd find /sys/devices -name uevent -exec sed -n 's/^MODALIAS=//p' '{}' + 2>/dev/null | sort -u
         debug_cmd lsmod
     fi
-
-    # Save the existing /lib64 so it  can be restored and used for eject at shutdown
-    test -d /lib64 && cp -a /lib64 /live/
 
     prep_ld_path
 
@@ -3423,6 +3426,13 @@ my_select() {
         data="${data}$dcnt:$lab\n"
 
         [ "$lab" =  "$_quit_" ] && lab=$bold_co$lab$nc_co
+
+        # Highlight "G" and "M" numerical suffix
+        if echo "$lab" | egrep -q "^[0-9]+[GM]iB$"; then
+            local num=${lab%[GM]iB}
+            local suffix=${lab#$num}
+            lab="$num $suffix"
+        fi
         [ $cnt = "$default" ] && lab=$(printf "%${width}s (%s)" "$lab" "$(cq  "$_default_")")
         display="${display}$(printf "$green%2d$white)$cyan %${width}s" $dcnt "$lab")\n"
     done
@@ -3860,7 +3870,6 @@ select_device() {
         pretty=$(printf "$format" "$cnt_lab" "$name_rev" "$name" "$size_rev" "$size_lab" \
             "$free_rev" "$free_lab" "$type_rev" "$type" "$rtype" "$model" "$label")
 
-
         local display="${display}$pretty\n"
 
         [ -z "$cnt_lab" ] && continue
@@ -3875,9 +3884,10 @@ Blkid
     echo
 
     if [ $cnt -le 1 ]; then
-        display="$header\n$display"
-        msg_nc "$display"
+        #display="$header\n$display"
+        #msg_nc "$display"
         warn  "No suitable devices were found."
+        press_enter
         return 1
     fi
 
@@ -4913,7 +4923,7 @@ create_persist_files() {
         local default_size rootfs_file=rootfs
         if [ "$WILL_REMASTER" ]; then
             default_size=$(stat -c %s $dir/rootfs 2>/dev/null)
-            msg 'default size: %s Meg' "$(nq $default_size)"
+            msg 'default size: %s MiB' "$(nq $default_size)"
             [ "$default_size" ] && default_size=$((default_size/1024/1024))
             rootfs_file=rootfs.new
         fi
@@ -4953,26 +4963,26 @@ _persist_makefs() {
     local free=$(free_space $mp)
     local avail=$((free - MKFS_FREE_MARGIN))
 
-    vmsg 6 '      Free space: %s Meg' $(nq $free)
-    vmsg 6 ' Available space: %s Meg' $(nq $avail)
+    vmsg 6 '      Free space: %s MiB' $(nq $free)
+    vmsg 6 ' Available space: %s MiB' $(nq $avail)
 
     [ "$orig_def_size" ] && [ $orig_def_size -gt $avail ] \
-        && warn  "Not enough room on Live device to create %s file of size %s Meg" \
+        && warn  "$_Not_enough_room_on_Live_device_to_create_X_file_of_size_Y_MiB_" \
             $(fq $file) $(nq $orig_def_size)
 
     local base_file=${file%%.*}
     local default_size=$(default_makefs_size $avail ${base_file}_SIZE_PARAM $orig_def_size)
 
-    vmsg 6 '    Default size: %s Meg' $(nq $default_size)
+    vmsg 6 '    Default size: %s MiB' $(nq $default_size)
 
     : ${default_size:=-1}
 
 
     # Make sure we don't exceed max size of 4G - 1 on vfat file systems
     mkdir -p $dir
-    local part_fstype=$(mntpnt_fstype $dir) mkfs_sizes=$MKFS_SIZES vfat
+    local part_fstype=$(mntpnt_fstype $dir) mkfs_sizes=$MKFS_SIZES is_vfat
     case $part_fstype in
-        vfat) vfat=true ;;
+        vfat) is_vfat=true ;;
            *) mkfs_sizes="$mkfs_sizes $BIGGER_SIZES" ;;
     esac
 
@@ -5016,9 +5026,9 @@ _persist_makefs() {
     #[ "$needed" ] && quit=
 
     heading  "$_create_X_persistence_file_" "$(fq $file)"
-    vmsg 1  "$_Default_size_X_Meg_Filesystem_type_Y_" $(nq $default_size) $(pq ext4)
-    vmsg 1  "$_This_default_size_will_leave_X_Meg_free_" $(nq $((avail - default_size)))
-    [ "$vfat" ] &&  warn  "Warning: this can take several minutes per Gig on a %s file system" $(pqw $part_fstype)
+    vmsg 1  "$_Default_size_X_MiB_Filesystem_type_Y_" $(nq $default_size) $(pq ext4)
+    vmsg 1  "$_This_default_size_will_leave_X_MiB_free_" $(nq $((avail - default_size)))
+    [ "$is_vfat" ] &&  warn  "Warning: this can take several minutes per Gig on a %s file system" $(pqw $part_fstype)
 
     if [ "$AUTO_MAKE_FS" ]; then
         auto_mode=true
@@ -5039,11 +5049,27 @@ _persist_makefs() {
         local title=$(printf  "$_Please_select_size_of_X_file_" $(pqw $file))
 
         echo
-        vmsg 1  "$_There_is_X_Meg_available_on_the_device_" $(nq $avail)
-        my_select "$title" fs_size 4 "$default_cnt" $sizes "$quit"
+        vmsg 1  "$_There_is_X_MiB_available_on_the_device_" $(nq $avail)
+
+        # Add "G" and "M" suffixes
+        local size_menu
+        for size in $sizes; do
+            local gig=$((size / 1024))
+            if [ $((size - gig * 1024)) -eq 0 ]; then
+                size_menu="$size_menu ${gig}GiB"
+            else
+                size_menu="$size_menu ${size}MiB"
+            fi
+        done
+
+        my_select "$title" fs_size 9 "$default_cnt" $size_menu "$quit"
         [ "$fs_size" =  "$_quit_" ] && return 1
 
-        vmsg 1  "$_Filesystem_size_X_Meg_" $(nq $fs_size)
+        # Remove "G" and "M" suffixes
+        [ -z "${fs_size%%*GiB}" ] && fs_size=$((${fs_size%GiB} * 1024))
+        fs_size=${fs_size%MiB}
+
+        vmsg 1  "$_Filesystem_size_X_MiB_" $(nq $fs_size)
 
         #title=$(printf "Please select file system for %s file" $(pqw $file))
         #echo
@@ -5051,7 +5077,7 @@ _persist_makefs() {
         #[ "$fs_type" = "quit" ] && return 1
         fs_type=ext4
     fi
-    vmsg 1  "$_Create_X_file_of_type_Y_and_size_Z_Meg_" "$(fq $file)" "$(pq $fs_type)" "$(nq $fs_size)"
+    vmsg 1  "$_Create_X_file_of_type_Y_and_size_Z_MiB_" "$(fq $file)" "$(pq $fs_type)" "$(nq $fs_size)"
 
     # Now do the actual work
 
@@ -5059,7 +5085,7 @@ _persist_makefs() {
 
     breakpoint m "before makefs"
 
-    [ "$vfat" ] &&  warn  "Warning: this can take several minutes per Gig on a %s file system" $(pqw $part_fstype)
+    [ "$is_vfat" ] &&  warn  "$_Warning_this_can_take_several_minutes_per_Gigabyte_on_a_X_file_system_" $(pqw $part_fstype)
     if ! time_cmd makefs $full_file $fs_type $fs_size $part_fstype; then
         err  "Failed to create filesystem.  Deleting %s file" $(pqe $file)
         rm -f $full_file
@@ -5210,7 +5236,7 @@ copy_persist_to_ram() {
         vmsg_nc 3 $tbar
         return 1
     fi
-    vmsg 5  "$_Copy_X_Megabytes_to_RAM_" "${num_co}$persist_used${m_co}"
+    vmsg 5  "$_Copy_X_MiB_to_RAM_" "${num_co}$persist_used${m_co}"
     if ! cp_dir $ROOTFS_MP $AUFS_RAM_MP 2>&1; then
          err  "Copy persistent root to RAM failed!  Will erase partial copy ..."
          rm -rf $AUFS_RAM_MP/*
@@ -5343,8 +5369,8 @@ offer_copy_home_dir() {
     local needed=$(du_size $real)
     local avail=$(avail_space $temp)
     local margin=$((avail - needed))
-    msg  "$_There_are_X_Meg_of_files_that_will_get_hidden_by_home_persistence_"  $(nq $needed)
-    msg  "$_There_are_X_Meg_free_on_the_home_persistence_device_"                $(nq $avail)
+    msg  "$_There_are_X_MiB_of_files_that_will_get_hidden_by_home_persistence_"  $(nq $needed)
+    msg  "$_There_are_X_MiB_free_on_the_home_persistence_device_"                $(nq $avail)
 
     if [ $margin -lt 50 ]; then
         msg  "$_Theres_not_enough_space_to_copy_all_the_files_"
@@ -5402,7 +5428,7 @@ copy_homefs() {
     local need_meg=$(used_space $cur_home_mp)
     local have_meg=$(all_space $new_home_mp)
     need_meg=$((need_meg + 10))
-    vmsg 6  "Have %s Megabytes free.  Need %s" "$(nq $have_meg)" "$(nq $need_meg)"
+    vmsg 6  "$_Have_X_MiB_free_Need_Y_" "$(nq $have_meg)" "$(nq $need_meg)"
     if [ "$need_meg" -gt "$have_meg" ]; then
         err  "Not enough room to copy home filesystem"
         return 1
@@ -5488,7 +5514,7 @@ fancy_prompt() {
         cat << Fancy_Stuff >> $bashrc
 
 #----- Added by live initrd init script
-LESS="-R"
+LESS="-R -i"
 [ -r $fp_prog ] && source $fp_prog
 [ -n "\$(alias $cmd)" ] && $prompt
 echo \$PATH | grep -q /live/bin || PATH=\$PATH:/etc/live/bin
@@ -5584,8 +5610,7 @@ prep_ld_path() {
 
     SET_ARCH=
     case $arch in
-          x86_64) prep_lib64 $dir
-                  ld_path=$LIVE_X64_LD_PATH
+          x86_64) ld_path=$LIVE_X64_LD_PATH
                   SET_ARCH=linux64           ;;
 
         i[3-8]86) ld_path=$LIVE_386_LD_PATH
@@ -5781,10 +5806,21 @@ update_store_file() {
 #
 #------------------------------------------------------------------------------
 write_log_files() {
-    local my_log=$1 final_log=$2 e=$(printf "\e")
-    mkdir -p $(dirname $final_log)
-    sed -r "s/$e\[[0-9;]+[mK]//g" $my_log > $final_log
-    cp $my_log $final_log.color
+    local my_log=$1 color_log=$2.color
+    mkdir -p $(dirname $color_log)
+    cp $my_log $color_log
+    decolor_file $color_log
+}
+
+#------------------------------------------------------------------------------
+#
+#------------------------------------------------------------------------------
+decolor_file() {
+    local file=$1  new=${1%.color}  e=$(printf "\e")
+
+    test -r $file || return
+    [ "$file" = "$new" ] && return
+    sed -r "s/$e\[[0-9;]+[mK]//g" $file > $new
 }
 
 #------------------------------------------------------------------------------
@@ -5850,6 +5886,15 @@ update_file() {
     test -e $src || return
     diff -q $src $dest &>/dev/null && return
     cp -a $src $dest
+}
+
+#------------------------------------------------------------------------------
+#
+#------------------------------------------------------------------------------
+press_enter() {
+    local ans enter="Enter"
+    msg  "$_Press_X_to_continue_" "$(pq "$enter")"
+    read ans
 }
 
 #------------------------------------------------------------------------------
@@ -6040,13 +6085,6 @@ prepare_switch_root() {
     local fbsys=$root_dir/lib/splash/sys
     mountpoint $fbsys &>/dev/null && umount $fbsys
 
-    # We had mucked with lib64 to be able to use programs in /aufs and /linux.
-    # Now restore it so we can call eject at the end of shutdown
-    if test -d /lib64; then
-        rm -r /lib64
-        mv /live/lib64 /
-    fi
-
     local dir old new
     for dir in bin config etc lib64 lib locale custom menus share; do
         old=$root_dir/$dir
@@ -6068,6 +6106,23 @@ prepare_switch_root() {
     PATH=$new_live/bin:$PATH
 
     (cd $new_root && mkdir -p sys proc dev/pts)
+}
+
+#------------------------------------------------------------------------------
+#
+#------------------------------------------------------------------------------
+dummy_translate() {
+    msg 'default size: %s Meg' "$(nq $default_size)"
+    vmsg 6  "Have %s Megabytes free.  Need %s" "$(nq $have_meg)" "$(nq $need_meg)"
+    vmsg 1  "$_Default_size_X_Meg_Filesystem_type_Y_" $(nq $default_size) $(pq ext4)
+    vmsg 1  "$_This_default_size_will_leave_X_Meg_free_" $(nq $((avail - default_size)))
+    warn  "Warning: this can take several minutes per Gig on a %s file system" $(pqw $part_fstype)
+    vmsg 1  "$_There_is_X_Meg_available_on_the_device_" $(nq $avail)
+    vmsg 1  "$_Filesystem_size_X_Meg_" $(nq $fs_size)
+    vmsg 1  "$_Create_X_file_of_type_Y_and_size_Z_Meg_" "$(fq $file)" "$(pq $fs_type)" "$(nq $fs_size)"
+    vmsg 5  "$_Copy_X_Megabytes_to_RAM_" "${num_co}$persist_used${m_co}"
+    msg  "$_There_are_X_Meg_of_files_that_will_get_hidden_by_home_persistence_"  $(nq $needed)
+    msg  "$_There_are_X_Meg_free_on_the_home_persistence_device_"                $(nq $avail)
 }
 
 #------------------------------------------------------------------------------
